# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'iOSBooks' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOSBooks
  pod 'PromiseKit'
  pod 'IQKeyboardManagerSwift'
  pod 'Kingfisher', "~>5.1"

  target 'iOSBooksTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick', '~> 2.1.0'
    pod 'Nimble', '~> 8.0.1'
  end

end
